version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./mongodb_data:/data/db

  back:
    container_name: back
    image: back
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb/mes-petits-chantiers

  front:
    container_name: front
    image: front
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
